name: reviewdog
on: [pull_request]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: detekt
        uses: alaegin/Detekt-Action@v1.18.1.2
        with:
          github_token: ${{ secrets.github_token }}
          reviewdog_filter: nofilter
          detekt_config: /detekt-config.yaml --build-upon-default-config
          fail_on_error: true
